#!/bin/bash
yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
Cyan="\033[96;1m"
Purple="\033[95;1m"
Green="\033[92;1m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
NC='\e[0m'
nama=$(cat /etc/xray/username)
# . Liner 
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

# Fungsi Backupp sebelum Reset
Backup() {
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
IP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
date=$(date +"%Y-%m-%d")
clear
rm -rf /root/backup
mkdir /root/backup
cp /etc/passwd backup/
cp /etc/group backup/
cp /etc/shadow backup/
cp /etc/gshadow backup/
cp /etc/crontab backup/
cp /etc/vmess/.vmess.db backup/
cp /etc/ssh/.ssh.db backup/
cp /etc/vless/.vless.db backup/
cp /etc/trojan/.trojan.db backup/
cp /etc/bot/.bot.db backup/
cp -r /etc/kyt/limit backup/
cp -r /etc/limit backup/qt/
cp -r /etc/vmess backup/
cp -r /etc/trojan backup/
cp -r /etc/vless backup/
cp -r /etc/slowdns backup/
cp -r /var/lib/kyt/ backup/kyt 
cp -r /etc/xray backup/xray
cp -r /var/www/html/ backup/html
cd /root
zip -r $IP-$date.zip backup > /dev/null 2>&1
rclone copy /root/$IP-$date.zip dr:backup/
url=$(rclone link dr:backup/$IP-$date.zip)
id=(`echo $url | grep '^https' | cut -d'=' -f2`)
link="https://drive.google.com/u/4/uc?id=${id}"
echo -e "
Detail Backup 
==================================
IP VPS        : $IP
Link Backup   : $link
Tanggal       : $date
==================================
" | mail -s "Backup Data" $email
rm -rf /root/backup
rm -r /root/$IP-$date.zip
clear
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
◇━━━━━━━━━━━━━━◇
<b>   ⚠️BACKUP NOTIF⚠️</b>
<b>     Detail Backup VPS</b>
◇━━━━━━━━━━━━━━◇
<b>IP VPS  :</b> ${IP} 
<b>DOMAIN  :</b> ${domain}
<b>Tanggal : $date</b>
◇━━━━━━━━━━━━━━◇
<b>Link Backup   :</b> $link
◇━━━━━━━━━━━━━━◇
Silahkan copy Link dan restore di VPS baru
BY BOT : @denisastore32
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo ""
clear
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
factreset() {
##----- Auto Remove Vmess
data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuid=$(grep -E "###" "/etc/vmess/.vmess.db" |  grep -wE ${user} | awk '{print $4}' | uniq )
    exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
        sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "d" /etc/vmess/.vmess.db
        rm -rf /etc/vmess/$user
        rm -f /etc/kyt/limit/vmess/ip/*
	    rm -f /etc/limit/vmess/*
	    rm -f /var/www/html/vmess-$user.txt
done

#----- Auto Remove Vless
data=($(cat /etc/xray/config.json | grep '^#&' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuid=$(grep -E "###" "/etc/vless/.vless.db" |  grep -wE ${user} | awk '{print $4}' | uniq )
    exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "d" /etc/vless/.vless.db
        rm -rf /etc/vless/$user
        rm -f /etc/kyt/limit/vless/ip/*
	    rm -f /etc/limit/vless/*
	    rm -f /var/www/html/vless-$user.txt
done

#----- Auto Remove Trojan
data=($(cat /etc/xray/config.json | grep '^#!' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuid=$(grep -E "###" "/etc/trojan/.trojan.db" |  grep -wE ${user} | awk '{print $4}' | uniq )
    exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
        sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "d" /etc/trojan/.trojan.db
        rm -rf /etc/trojan/$user
        rm -f /etc/kyt/trojan/ip/*
	    rm -f /etc/limit/trojan/*
	    rm -f /var/www/html/trojan-$user.txt
		sed -i "d" /etc/xray/.lock.db
		sed -i "d" /etc/xray/.userall.db
done

#----- Auto Remove SS
data=($(cat /etc/xray/config.json | grep '^#!#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#!# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
		uuid=$(grep -E "^},{" "/etc/xray/config.json" |  grep -wE '"'"${user}"'"' | cut -d " " -f 2 | cut -d '"' -f 2 | uniq )
        sed -i "/^#!# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/,/^},{/d" /etc/shadowsocks/.shadowsocks.db
        rm -rf /etc/shadowsocks/$user
        rm -f /etc/kyt/shadowsocks/ip/$user
	    rm -f /etc/limit/shadowsocks/$user
	    rm -f /var/www/html/sodosokws-$user.txt
done
systemctl restart xray

##------ Auto Remove SSH
data=( `awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd `)
for user in "${data[@]}"
do
        userdel -f "$user"
	    echo -n > /etc/xray/.userall.db
        echo -n > /etc/ssh/.ssh.db
        rm -f /etc/ssh/${user}
        rm -f /etc/kyt/limit/ssh/ip/*
	    rm -f /var/www/html/*.txt
		rm -rf /etc/limit/*
done
systemctl reload ssh
}
clear
echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m  WELCOME TO RESET FACTORY $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
read -p "   VERIFIKASI ADMIN :   " host11
if [[ $host11 = @denisa32 ]]; then
clear
echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m  WELCOME TO RESET FACTORY $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
echo -e " ${Red}PENTING HAL INI AKAN MENYEABKAN SEMUA AKUN $NC"
echo -e " ${Red}PADA SERVER ANDA HILANG! APAKAH ANDA AKAN MELANJUTKAN? $NC"
read -p " MASUKAN PILIHAN Y/N :   " arg
if [[ $arg == 'Y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  sleep 1
  echo -e "${green}START. . . $NC"
elif [[ $arg == 'y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  sleep 1
  echo -e "${Blue}START . . .$NC"
elif [[ $arg == 'N' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  menu
  exit 0
elif [[ $arg == 'n' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  exit 0
else
  echo -e "${RED}Argumen Tidak Diketahui! $NC"
  sleep 1
  clear
  exit 0
fi
clear
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m      RESET FACTORY $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo -e ""
echo -e " \033[1;91m Factory Reset Sedang Berlangsung!!\033[1;37m"
fun_bar 'backup' 'factreset'
echo -e "   ${BLUE}_______________________________$NC"
echo -e ""
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
else
clear
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
	echo ""
	echo -e "	\033[0;33mKembali Ke Menu Dalam 3 Detik\033[0m"
    sleep 3
    menu
fi