#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
BLUE="\033[4;34m"
BG_BLU="\033[44;1m" # BG BIRU
Xark='\e[0m'
GREN="\033[92m"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/denisa32/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
function baris_panjang() {
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}
function ATAS() {
  echo -e     "${ungu}         SSH-Dropbear-OpenVPN           ${Xark} "
}
function  MEMBER() {
  echo -e  " ${BG_BLU}                MEMBER                 ${Xark}"
}
function  LOCK_UNLOCK() {
  echo -e  " ${BG_BLU}             LOCK & UNLOCK             ${Xark}"
}
function  LIMIT() {
  echo -e  " ${BG_BLU}                 LIMIT                 ${Xark}"
}
function  OTHER() {
  echo -e  " ${BG_BLU}                 OTHER                 ${Xark}"
}

# . Create Ssh
function Create_Ssh() {
  add-ssh
}

# . Create Triall
function Create_Trial() {
  trial-ssh
}

# . Hapus akun ssh
function Delete_Ssh(){
  del-ssh
}

# . List Member ssh
function List_Member() {
  member-ssh
}

# . Auto Kill ssh
function Auto_Kill() {
  auto-kill
}

# . Check user Login
function Check_Mullog() {
  limitssh-ip
}

# . Delete Expiry
function Delete_Exp() {
  delexp
}

# . Changes Limit
function Changes_Limit() {
  Lt-on-off
}

# . Limit On off
function Limit_On_Off() {
  Lt-on-off
}

#. Renew Ssh
function Renew_Ssh() {
  renew-ssh
}

# . Lock Ssh
function Lock() {
  lock
}

# . Unlock Ssh
function Unlock() {
  unlock
}

# . Detail Akun Ssh
function Details_Account(){
  user-ssh
}

function Monitor_Ssh() {
  ceklim
}

function Recovery_Ssh() {
  recover
}

# . Banner Ssh
function Banner() {
  baris_panjang
  ATAS
  baris_panjang
}
function Menu_Features() {
  baris_panjang
  echo -e " 01.)  Check Users Login"
  echo -e " 02.)  Create Accounts"
  echo -e " 03.)  Delete Accounts"
  echo -e " 04.)  Renew Accounts"
  echo -e " 05.)  Trial Accounts"
  echo -e " 06.)  Recovery Accounts"
  baris_panjang
  MEMBER
  baris_panjang
  echo -e " 07.)  List Member Accounts"
  echo -e " 08.)  List Expired Accounts"
  baris_panjang
  LOCK_UNLOCK
  baris_panjang
  echo -e " 09.)  Lock Accounts"
  echo -e " 10.)  Unlock Accounts"
  baris_panjang
  LIMIT
  baris_panjang
  echo -e " 11.) Edit Limit IP Account"
  echo -e " 12.) Limit IP On Off Accounts"
  baris_panjang
  OTHER
  baris_panjang
  echo -e " 13.) Auto Kill Accounts "
  echo -e " 14.) Detail Accounts"
  baris_panjang
  echo -e " 15.) Back to Menu"
  baris_panjang
  baris_panjang
}

Banner
Menu_Features
read -p "Select From Options [1-15] :  " Ltt
case $Ltt in
1) clear ; Monitor_Ssh ;;
2) clear ; Create_Ssh ;;
3) clear ; Delete_Ssh ;;
4) clear ; renew-ssh ;;
5) clear ; Create_Trial ;;
6) clear ; Recovery_Ssh ;;
7) clear ; List_Member ;;
8) clear ; Delete_Exp ;;
9) clear ; Lock ;;
10) clear ; Unlock ;;
11) clear ; ganti-ip-ssh ;;
12) clear ; Limit_On_Off ;;
13) clear ; Check_Mullog ;;
14) clear ; Details_Account ;;
15) clear ; menu ;;
*) exit ;;
esac
