#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
r="\033[1;91m"
BG_BLU="\033[44;1m" # BG BIRU
GREN="\033[92m"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/denisa32/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
echo -e "══════════════════════════" | lolcat
echo -e " <= UUID X-RAY ACCOUNT =>"
echo -e "══════════════════════════" | lolcat
grep -oP '(?<=id": ")[^"]+' /etc/xray/*.json | sort -u
echo -e "══════════════════════════" | lolcat
read -p "Input Old UUID Account: " user
read -p "Input New UUID Account: " uuid
sed -i "s|\"id\": \"$user\"|\"id\": \"$uuid\"|" /etc/xray/*.json
systemctl restart xray
clear
echo -e "══════════════════════════" | lolcat
echo -e " <= SUCCES CHANGE UUID =>"
echo -e "══════════════════════════" | lolcat
echo -e "OLD UUID ACCOUNT: $user "
echo -e "NEW UUID ACCOUNT: $uuid "
echo -e "══════════════════════════" | lolcat
read -p "Enter Back To Menu"
menu